
# ZEGGS
train_data_path: "/apdcephfs/share_1290939/shaolihuang/ykcheng/MS_RP/AGDM/BEAT/trimmed_english_allbeats_res_emo/train/train_lmdb/train_lmdb"     # speaker_1_state_0
val_data_path: "/apdcephfs/share_1290939/shaolihuang/ykcheng/MS_RP/AGDM/BEAT/trimmed_english_allbeats_res_emo/val/val_lmdb/val_lmdb"

# 60 fps + normalized
data_mean: "/apdcephfs/share_1290939/shaolihuang/ykcheng/MS_RP/AGDM/BEAT/trimmed_english_allbeats_res_emo/mean.npz"
data_std: "/apdcephfs/share_1290939/shaolihuang/ykcheng/MS_RP/AGDM/BEAT/trimmed_english_allbeats_res_emo/std.npz"

n_poses: 88     # 88 -> 20*60
n_codes: 30
motion_resampling_framerate: 20     # 20 -> 60
subdivision_stride: 10      # 10 -> 200
batch_size: 300       # 384 -> 32
loader_workers: 12
epochs: 500     # 500 -> 10
save_per_epochs: 25     # 20 -> 1
#model_save_path: "./output/train_beat_semges_joint"  #classifier emotion
model_save_path: "./output/train_new_sem_joints_emb"   #sem-ges-joint embedding new!!!!!
name: "DiffuseStyleGesture"
log_interval: 50
weight_decay: 0.0
lr_anneal_steps: 0
#save_dir: "./zeggs_mymodel3_wavlm_new_1gpu"
#save_dir: "/apdcephfs/share_1290939/shaolihuang/ykcheng/DiffCoSG/new3/DiffuseStyleGesture/main/mydiffusion_zeggs/mydiffusion_zeggs/beats_SemiGest_all_speakers"
save_dir: "/apdcephfs/share_1290939/shaolihuang/ykcheng/DiffCoSG/new2/DiffuseStyleGesture/main/mydiffusion_zeggs/beats_all_ijcai_resume"
audio_feat: "wavlm"     # wav encoder; mfcc; wavlm

lr: 0.00003     # 0.00003 ->
betas: [0.5, 0.999]
milestones: [100, 200]
gamma: 0.1

